[package]
name = "bifrost"
version = "0.1.0"
edition = "2024"
default-run = "bifrost"

[dependencies]
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["io-std", "net", "macros", "rt-multi-thread", "signal", "time", "tracing"] }
tokio-util = { version = "0.7.15", features = ["codec", "io-util", "rt"] }

[[bin]]
name = "bifrost"
path = "src/main.rs"

[[bin]]
name = "bifrost-client"
path = "src/client.rs"
